apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  namespace: default
spec:
  selector:
    matchLabels:
      run: gke-test
  template:
    metadata:
      labels:
        run: gke-test
    spec:
      containers:
      - image: justo-dev-image
        imagePullPolicy: IfNotPresent
        name: gke-test
        ports:
        - containerPort: 8000
          protocol: TCP
