commonLabels:
  app: gke-test

resources:
- service.yml
- deployment.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: //
- name: eu.gcr.io/asd/asd
  newTag: "1"
- name: justo-dev-image
  newName: //
